### ISSUE TITLE
Build fails under GHC 9 due to TyVarBndr specificity.

### ISSUE THREAD

**Issue by galenhuntington** [nikita-volkov/contravariant-extras#8]
As of template-haskell 2.17, `TyVarBndr` takes a type argument:
https://downloads.haskell.org/~ghc/9.0.1-alpha1/docs/html/libraries/template-haskell-2.17.0.0/Language-Haskell-TH.html#t:TyVarBndr

This means this package fails to build because `PlainTV` requires a new specificity argument.

This could presumably be arranged with CPP, but, given this package's current conventions, it might be preferable to add a compatibility function to `TemplateHaskell.Compat.V0208`.

**Comment by nikita-volkov** [comment]
I've released the updated compatibility package. Thanks for the PR!

**Comment by galenhuntington** [comment]
Actually, this is a separate issue from the one fixed in https://github.com/nikita-volkov/template-haskell-compat-v0208/pull/1, although they have the same cause (the `TyVarBndr` kind change).

**Comment by galenhuntington** [comment]
Here is the error I get (this is with the fix in nikita-volkov/template-haskell-compat-v0208#1):

```
[2 of 7] Compiling Contravariant.Extras.TH ( library/Contravariant/Extras/TH.hs, dist/build/Contravariant/Extras/TH.o, dist/build/Contravariant/Extras/TH.dyn_o )

library/Contravariant/Extras/TH.hs:141:19: error:
    • Couldn't match type: flag0 -> TyVarBndr flag0
                     with: TyVarBndr Specificity
      Expected: [TyVarBndr Specificity]
        Actual: [flag0 -> TyVarBndr flag0]
    • In the first argument of ‘ForallT’, namely ‘vars’
      In the expression: ForallT vars cxt type_
      In an equation for ‘type_’:
          type_
            = ForallT vars cxt type_
            where
                fName = mkName "f"
                aNames
                  = map aName (enumFromTo 1 arity)
                  where
                      aName index = mkName (showString "a" (show index))
                vars = map PlainTV (fName : aNames)
                cxt
                  = [pred]
                  where
                      pred = Compat.classP ... ...
                ....
    • Relevant bindings include
        vars :: [flag0 -> TyVarBndr flag0]
          (bound at library/Contravariant/Extras/TH.hs:150:13)
    |
141 |           ForallT vars cxt type_
    |                   ^^^^
```

The problem is that `PlainTV` needs two arguments as of TH 2.17, and the second needs to be of type [Specificity](https://downloads.haskell.org/~ghc/9.0.1-alpha1/docs/html/libraries/template-haskell-2.17.0.0/Language-Haskell-TH.html#t:Specificity) (probably `SpecifiedSpec`) for use with `ForAllT`.

**Comment by nikita-volkov** [comment]
How about the latest commit? Can you check if it solves the issue?

**Comment by galenhuntington** [comment]
It does not, unfortunately.  `plainTV` produces a `TyVarBndr ()`, whereas `ForAllT` needs a `TyVarBndr Specificity`.  This is basically what I tried first too, but GHC didn't want to make it so easy.

Here's the error:

```
library/Contravariant/Extras/TH.hs:148:31: error:
    • Couldn't match type ‘()’ with ‘Specificity’
      Expected: [TyVarBndr Specificity]
        Actual: [TyVarBndr ()]
    • In the first argument of ‘ForallT’, namely ‘vars’
      In the expression: ForallT vars cxt type_
      In an equation for ‘contrazipType’:
          contrazipType arity
            = ForallT vars cxt type_
            where
                fName = mkName "f"
                aNames
                  = map aName (enumFromTo 1 arity)
                  where
                      aName index = mkName (showString "a" (show index))
                vars = map plainTV (fName : aNames)
                cxt
                  = [pred]
                  where
                      pred = Compat.classP ... ...
                ....
    |
148 | contrazipType arity = ForallT vars cxt type_ where
    |                               ^^^^
```

I was thinking that maybe a `Compat.plainTVSpecified` function could be added to `template-haskell-compat-v0208`, which would be either `PlainTV` or `flip PlainTV SpecifiedSpec`.

**Comment by nikita-volkov** [comment]
Sounds good. Please check out the latest commit

**Comment by galenhuntington** [comment]
Yup, it's working now!  🎉 🎉 🎉

**Comment by nikita-volkov** [comment]
Great! I've released it.

Thanks for your input and PR!
